# Generated by Django 2.2.5 on 2019-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190930_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(2, 'Premium Member'), (3, 'Guest Member'), (1, 'Regular member')], default=1),
        ),
    ]
