# Generated by Django 2.2.5 on 2019-11-17 07:54

from django.db import migrations, models
import myapp.validator


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191114_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.validator.maxvaluevalidator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(2, 'Premium Member'), (3, 'Guest Member'), (1, 'Regular member')], default=1),
        ),
    ]
