# Generated by Django 2.2.5 on 2019-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20191118_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(3, 'Guest Member'), (2, 'Premium Member'), (1, 'Regular member')], default=1),
        ),
    ]
