# Generated by Django 2.2.5 on 2019-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20191125_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(2, 'Premium Member'), (1, 'Regular member'), (3, 'Guest Member')], default=1),
        ),
    ]
