# Generated by Django 2.2.5 on 2019-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20191130_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(2, 'Premium Member'), (1, 'Regular member'), (3, 'Guest Member')], default=1),
        ),
    ]
